# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='minutes_file',
            field=models.FileField(upload_to=''),
        ),
    ]
